manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: prog13
      url-base: https://github.com/prog13
    - name: janpfischer
      url-base: https://github.com/janpfischer
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-mod
      remote: prog13
      revision: main
    - name: nice-view-battery
      remote: prog13
      revision: main
    - name: urchin-zmk-module
      remote: prog13
      revision: dongle
    - name: totem-zmk-module
      remote: prog13
      revision: main
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: upgrade-4.1
  self:
    path: config
